### ISSUE TITLE
error through multiple servlet registrations

### ISSUE THREAD

**Issue by maggu2810** [openhab/jupnp#18]
After changing the start levels of the OSGi bundles I got the following error:

<pre>2015-02-09 18:18:14,290 | ERROR | FelixStartLevel  | tpServiceServletContainerAdapter | 132 - org.jupnp - 2.0.0.201501291005 | Failed to register UPnP servlet!
org.osgi.service.http.NamespaceException: Servlet with alias already registered
	at org.apache.felix.http.base.internal.handler.HandlerRegistry.addServlet(HandlerRegistry.java:63)
	at org.apache.felix.http.base.internal.service.HttpServiceImpl.registerServlet(HttpServiceImpl.java:102)
	at org.jupnp.transport.impl.osgi.HttpServiceServletContainerAdapter.registerServlet(HttpServiceServletContainerAdapter.java:71)
	at org.jupnp.transport.impl.AsyncServletStreamServerImpl.init(AsyncServletStreamServerImpl.java:71)
	at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:426)
	at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:129)
	at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:201)
	at org.jupnp.UpnpServiceImpl.activate(UpnpServiceImpl.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483)[:1.8.0_31]
	at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:231)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:39)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:624)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:508)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.helper.ActivateMethod.invoke(ActivateMethod.java:149)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:315)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:127)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:871)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:838)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:777)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:320)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:231)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:327)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.getService(Felix.java:3576)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:468)[org.apache.felix.framework-4.4.1.jar:]
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:38)[117:com.eclipsesource.jaxrs.publisher:4.1.0.201407131319]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:932)[karaf-org.osgi.core.jar:]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:864)[karaf-org.osgi.core.jar:]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[karaf-org.osgi.core.jar:]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)[karaf-org.osgi.core.jar:]
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:894)[karaf-org.osgi.core.jar:]
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:943)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:794)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:544)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4445)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.registerService(Felix.java:3431)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:346)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:1003)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:992)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:134)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:1044)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:841)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:419)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.config.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:376)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.BundleComponentActivator.initialize(BundleComponentActivator.java:172)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.BundleComponentActivator.<init>(BundleComponentActivator.java:120)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:258)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.Activator.access$000(Activator.java:45)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:185)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)[81:org.apache.felix.scr:1.8.2]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:479)[81:org.apache.felix.scr:1.8.2]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:414)[81:org.apache.felix.scr:1.8.2]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)[karaf-org.osgi.core.jar:]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443)[81:org.apache.felix.scr:1.8.2]
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:869)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:790)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:515)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2100)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)[org.apache.felix.framework-4.4.1.jar:]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_31]</pre>

The init function of org.jupnp.transport.impl.AsyncServletStreamServerImpl log to info, so I set the jupnp log level to info and grep for upnp (ignore case) on startup.

<pre>2015-02-10 09:50:39,388 | INFO  | FelixStartLevel  | UpnpServiceImpl                  | 135 - org.jupnp - 2.0.0.201501291005 | Starting UPnP service...
2015-02-10 09:50:39,415 | INFO  | FelixStartLevel  | tpServiceServletContainerAdapter | 135 - org.jupnp - 2.0.0.201501291005 | Registering UPnP callback servlet as /upnpcallback
2015-02-10 09:50:39,419 | INFO  | FelixStartLevel  | tpServiceServletContainerAdapter | 135 - org.jupnp - 2.0.0.201501291005 | Registering UPnP callback servlet as /upnpcallback
2015-02-10 09:50:39,422 | ERROR | FelixStartLevel  | tpServiceServletContainerAdapter | 135 - org.jupnp - 2.0.0.201501291005 | Failed to register UPnP servlet!
        at org.jupnp.transport.impl.osgi.HttpServiceServletContainerAdapter.registerServlet(HttpServiceServletContainerAdapter.java:71)
        at org.jupnp.transport.impl.AsyncServletStreamServerImpl.init(AsyncServletStreamServerImpl.java:71)
        at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:426)
        at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:129)
        at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:201)
        at org.jupnp.UpnpServiceImpl.activate(UpnpServiceImpl.java:218)</pre>

So, the UPnP callback servlet is registered twice.

There are a lot of bundles, so I could be wrong, but the sonos and hue binding are using jupnp.
If the start level of jupnp is lower then the ESH / OH2 stuff, the error does not hit.
If the start level of jupnp, sonos, hue (and a lot of other stuff) is set to the same level the error hits.

So, I think it is not intendet to ignore error messages, is there a better way as changing the start level?

**Comment by kaikreuzer** [comment]
Agreed, this needs to be fixed. Also reported at https://bugs.eclipse.org/bugs/show_bug.cgi?id=458526

**Comment by maggu2810** [comment]
Some similar error message was solved on another project on tracking if the servlet was already initialized: https://opencast.jira.com/secure/attachment/11775/MH-6135.diff
Do not know the best approach for jupnp.

**Comment by kaikreuzer** [comment]
I just found the problem - it actually only occurs, if you have multiple network interfaces on your computer - this is why I did not see it before. It tries to register the servlet for each network interface once, but for the OSGi HTTP service this should of course only happen once. Will fix it soon.

**Comment by maggu2810** [comment]
Ok, that sounds reasonable.
Do you know why the error is influenced by the starting level? The network interfaces are the same ;-)

**Comment by kaikreuzer** [comment]
I'd assume this is due to another bug with the configuration handling. I expect that in this case the OSGi component is not even correctly started - or is it?

**Comment by maggu2810** [comment]
It is marked "active".
I will test it (same start level for hue, sonos and jupnp), if this one is fixed.
Thank you.

**Comment by kaikreuzer** [comment]
Fixed and just deployed a new build with this fix on the p2 update site.

**Comment by maggu2810** [comment]
I added a small comment to the commit...

**Comment by JochenHiller** [comment]
I will reopen this issue based on comment at https://community.openhab.org/t/failed-to-register-upnp-servlet-at-start-of-openhab2-demo-help/2360

This PR https://github.com/openhab/jupnp/pull/24 seems to miss the changes from this issue fixed. In HttpServiceServletContainerAdapter there was a getInstance() introduced which re-uses the adapter and avoid registration of /upnpcallback multiple times.

**Comment by kaikreuzer** [comment]
Fixed again through https://github.com/openhab/jupnp/commit/bd109b62e5bc2e8ea01e0c72e6cef767b29fadfa
